spring.application.name=instituto-ecoar
server.port=${PORT:8080}

spring.thymeleaf.cache=false
spring.web.resources.cache.period=3600

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:ecoarinstitutobr@gmail.com}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

ecoar.mail.to=${MAIL_TO:ecoarinstitutobr@gmail.com}
